runs-on: ubuntu-latest
steps:
- name: Install SSH key
  uses: shimataro/ssh-key-action@v2
  with:
    key: ${{ secrets.MY_LINODESERVER }}
    

    
- name: rsync over ssh
  run: rsync ./rrr/ root@172.105.55.134:/var/www/html/
